/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author mello
 */
public class Jogo extends javax.swing.JFrame {

    Random random = new Random();
    int numeroSecreto = random.nextInt(10) + 1;

    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumberUsuario = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        botaoEnviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(305, 214));
        getContentPane().setLayout(null);

        NumberUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NumberUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(NumberUsuario);
        NumberUsuario.setBounds(30, 70, 220, 30);

        botaoVoltar.setText("Voltar");
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar);
        botaoVoltar.setBounds(170, 110, 80, 23);

        botaoEnviar.setText("Enviar");
        botaoEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEnviar);
        botaoEnviar.setBounds(30, 110, 80, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/newpackage/telaJogo (1).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 290, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumberUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberUsuarioActionPerformed


    }//GEN-LAST:event_NumberUsuarioActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        // TODO add your handling code here:

        String input = NumberUsuario.getText();
        int numero = Integer.parseInt(input);

        if (numero == numeroSecreto) {
            JOptionPane.showMessageDialog(this, "Parabéns! Você adivinhou o número.");
            
             Random random = new Random();
                numeroSecreto = random.nextInt(10) + 1;
            
        } else if (numero >= numeroSecreto) {
            JOptionPane.showMessageDialog(this, "O numero é menor: ");
        } else if (numero <= numeroSecreto) {
            JOptionPane.showMessageDialog(this, "O numero é maior: ");
        }

    }

    {

    }//GEN-LAST:event_botaoEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumberUsuario;
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
