/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author mello
 */
public class Jogo extends javax.swing.JFrame {

    Random random = new Random();
    int numeroSecreto = random.nextInt(10) + 1;
    int tentativas = 0;
    int tent = 0;
    int acertos = 0;
    
    
    String str;

    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();
        setLocationRelativeTo(null);

        str = JOptionPane.showInputDialog(null, "Qual seu nome? ");
        Integer name = Integer.getInteger(str);
        if (str.getBytes().equals("Cancelar")) {

        } else {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumberUsuario = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        botaoEnviar = new javax.swing.JButton();
        TxtTent = new javax.swing.JTextField();
        TxtJoga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(305, 214));
        getContentPane().setLayout(null);

        NumberUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NumberUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberUsuarioActionPerformed(evt);
            }
        });
        NumberUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumberUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(NumberUsuario);
        NumberUsuario.setBounds(30, 70, 220, 30);

        botaoVoltar.setText("Voltar");
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar);
        botaoVoltar.setBounds(170, 110, 80, 23);

        botaoEnviar.setText("Enviar");
        botaoEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEnviar);
        botaoEnviar.setBounds(30, 110, 80, 23);

        TxtTent.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtTent.setEnabled(false);
        TxtTent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTentActionPerformed(evt);
            }
        });
        getContentPane().add(TxtTent);
        TxtTent.setBounds(90, 140, 20, 30);

        TxtJoga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtJoga.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtJoga.setEnabled(false);
        TxtJoga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtJogaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtJoga);
        TxtJoga.setBounds(230, 140, 20, 30);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Jogadas:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 144, 68, 20);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Tentativas:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 144, 67, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/newpackage/telaJogo (1).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 290, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumberUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberUsuarioActionPerformed
        // TODO add your handling code here:

        String cara = "0123456789";
        if (!cara.contains(e.getKeyChar() + "")) {
            e.consume();
        }


    }//GEN-LAST:event_NumberUsuarioActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:

        Object[] opcoes = {"Sim", "Não",};
        int escolha = JOptionPane.showOptionDialog(null, "Você Teve " + acertos + " acertos " + " e " + tent + " Erros " + "\n" + "Deseja mesmo voltar?",
                "Deseja mesmo voltar?", JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE, null, opcoes, opcoes[0]);
        if(escolha == 0){
        dispose();
            
            
        }else{
            
        }


    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        // TODO add your handling code here:

        String input = NumberUsuario.getText();
        int numero = Integer.parseInt(input);
        tentativas++;
        tent++;

        TxtTent.setText("" + acertos);
        TxtJoga.setText("" + tentativas);

        if (numero == numeroSecreto) {
            JOptionPane.showMessageDialog(this, "Parabéns " + str + "!!!" + "\n" + " Você adivinhou o número em " + tentativas + " tentativas."
                    + "\n" + "\n" + "Tentativas Totais: " + tent);

            Random random = new Random();
            numeroSecreto = random.nextInt(10) + 1;
            tentativas = 0;
            acertos++;

        } else if (numero >= numeroSecreto) {
            JOptionPane.showMessageDialog(this, "O numero secreto é menor: ");
        } else if (numero <= numeroSecreto) {
            JOptionPane.showMessageDialog(this, "O numero secreto é maior: ");
        }

    }

    {

    }//GEN-LAST:event_botaoEnviarActionPerformed

    private void TxtTentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTentActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_TxtTentActionPerformed

    private void TxtJogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJogaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtJogaActionPerformed

    private void NumberUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumberUsuarioKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_NumberUsuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumberUsuario;
    private javax.swing.JTextField TxtJoga;
    private javax.swing.JTextField TxtTent;
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
